# Generated by Django 4.2.3 on 2023-08-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
